"""Normalisateur de noms d'équipes Football-Data.co.uk.

Chaque CSV peut contenir des variantes de noms (ex: "Man City" vs "Manchester City").
Ce module mappe toutes les variantes vers un nom canonique unique par ligue.
"""

from loguru import logger


# Dictionnaire de normalisation par ligue
# Clé = variante dans le CSV, Valeur = nom canonique
TEAM_ALIASES: dict[str, dict[str, str]] = {
    "E0": {
        "Arsenal": "Arsenal",
        "Aston Villa": "Aston Villa",
        "Barnsley": "Barnsley",
        "Birmingham": "Birmingham City",
        "Birmingham City": "Birmingham City",
        "Blackburn": "Blackburn Rovers",
        "Blackburn Rovers": "Blackburn Rovers",
        "Blackpool": "Blackpool",
        "Bolton": "Bolton Wanderers",
        "Bolton Wanderers": "Bolton Wanderers",
        "Bournemouth": "AFC Bournemouth",
        "AFC Bournemouth": "AFC Bournemouth",
        "Brentford": "Brentford",
        "Brighton": "Brighton & Hove Albion",
        "Brighton and Hove Albion": "Brighton & Hove Albion",
        "Brighton & Hove Albion": "Brighton & Hove Albion",
        "Burnley": "Burnley",
        "Cardiff": "Cardiff City",
        "Cardiff City": "Cardiff City",
        "Chelsea": "Chelsea",
        "Crystal Palace": "Crystal Palace",
        "Derby": "Derby County",
        "Derby County": "Derby County",
        "Everton": "Everton",
        "Fulham": "Fulham",
        "Huddersfield": "Huddersfield Town",
        "Huddersfield Town": "Huddersfield Town",
        "Hull": "Hull City",
        "Hull City": "Hull City",
        "Leeds": "Leeds United",
        "Leeds United": "Leeds United",
        "Leicester": "Leicester City",
        "Leicester City": "Leicester City",
        "Liverpool": "Liverpool",
        "Luton": "Luton Town",
        "Luton Town": "Luton Town",
        "Man City": "Manchester City",
        "Manchester City": "Manchester City",
        "Man Utd": "Manchester Utd",
        "Man United": "Manchester Utd",
        "Manchester United": "Manchester Utd",
        "Manchester Utd": "Manchester Utd",
        "Middlesbrough": "Middlesbrough",
        "Newcastle": "Newcastle Utd",
        "Newcastle United": "Newcastle Utd",
        "Newcastle Utd": "Newcastle Utd",
        "Norwich": "Norwich City",
        "Norwich City": "Norwich City",
        "Nott'm Forest": "Nottingham Forest",
        "Nottingham Forest": "Nottingham Forest",
        "QPR": "Queens Park Rangers",
        "Queens Park Rangers": "Queens Park Rangers",
        "Reading": "Reading",
        "Sheffield United": "Sheffield United",
        "Sheffield Weds": "Sheffield Wednesday",
        "Southampton": "Southampton",
        "Stoke": "Stoke City",
        "Stoke City": "Stoke City",
        "Sunderland": "Sunderland",
        "Swansea": "Swansea City",
        "Swansea City": "Swansea City",
        "Tottenham": "Tottenham",
        "Spurs": "Tottenham",
        "Watford": "Watford",
        "West Brom": "West Bromwich Albion",
        "West Bromwich Albion": "West Bromwich Albion",
        "West Ham": "West Ham",
        "West Ham United": "West Ham",
        "Wigan": "Wigan Athletic",
        "Wigan Athletic": "Wigan Athletic",
        "Wolves": "Wolverhampton",
        "Wolverhampton": "Wolverhampton",
    },
    "SP1": {
        "Athletic Bilbao": "Athletic Bilbao",
        "Athletic Club": "Athletic Bilbao",
        "Atletico Madrid": "Atletico Madrid",
        "Atl Madrid": "Atletico Madrid",
        "Barcelona": "Barcelona",
        "Betis": "Real Betis",
        "Real Betis": "Real Betis",
        "Celta Vigo": "Celta Vigo",
        "Celta": "Celta Vigo",
        "Deportivo": "Deportivo La Coruna",
        "Deportivo La Coruna": "Deportivo La Coruna",
        "Eibar": "Eibar",
        "Espanyol": "Espanyol",
        "Getafe": "Getafe",
        "Girona": "Girona",
        "Girona FC": "Girona",
        "Granada": "Granada",
        "Huesca": "Huesca",
        "La Coruna": "Deportivo La Coruna",
        "Las Palmas": "Las Palmas",
        "Leganes": "Leganes",
        "Levante": "Levante",
        "Malaga": "Malaga",
        "Mallorca": "Mallorca",
        "Osasuna": "Osasuna",
        "Real Madrid": "Real Madrid",
        "Real Sociedad": "Real Sociedad",
        "Real Valladolid": "Real Valladolid",
        "Sevilla": "Sevilla",
        "Sociedad": "Real Sociedad",
        "Sporting Gijon": "Sporting Gijon",
        "Valencia": "Valencia",
        "Valladolid": "Real Valladolid",
        "Villarreal": "Villarreal",
    },
    "I1": {
        "AC Milan": "AC Milan",
        "Inter": "Inter Milan",
        "Inter Milan": "Inter Milan",
        "Juventus": "Juventus",
        "Lazio": "Lazio",
        "Napoli": "Napoli",
        "Roma": "Roma",
        "AS Roma": "Roma",
        "Fiorentina": "Fiorentina",
        "Torino": "Torino",
        "Atalanta": "Atalanta",
        "Sampdoria": "Sampdoria",
        "Sassuolo": "Sassuolo",
        "Genoa": "Genoa",
        "Udinese": "Udinese",
        "Bologna": "Bologna",
        "Cagliari": "Cagliari",
        "Empoli": "Empoli",
        "Lecce": "Lecce",
        "Parma": "Parma",
        "Verona": "Verona",
        "Hellas Verona": "Verona",
        "Verona": "Verona",
        "Chievo": "Chievo Verona",
        "Chievo Verona": "Chievo Verona",
        "SPAL": "SPAL",
        "Brescia": "Brescia",
        "Benevento": "Benevento",
        "Frosinone": "Frosinone",
        "Palermo": "Palermo",
        "Pescara": "Pescara",
        "Crotone": "Crotone",
        "Spezia": "Spezia",
        "Venezia": "Venezia",
        "Salernitana": "Salernitana",
        "Monza": "Monza",
        "Lazio": "Lazio",
    },
    "D1": {
        "Bayern Munich": "Bayern Munich",
        "FC Bayern": "Bayern Munich",
        "Bayern Munchen": "Bayern Munich",
        "Dortmund": "Borussia Dortmund",
        "Borussia Dortmund": "Borussia Dortmund",
        "BVB Dortmund": "Borussia Dortmund",
        "Leverkusen": "Bayer Leverkusen",
        "Bayer Leverkusen": "Bayer Leverkusen",
        "Wolfsburg": "Wolfsburg",
        "VfL Wolfsburg": "Wolfsburg",
        "RB Leipzig": "RB Leipzig",
        "Leipzig": "RB Leipzig",
        "Frankfurt": "Eintracht Frankfurt",
        "Eintracht Frankfurt": "Eintracht Frankfurt",
        "Monchengladbach": "Borussia Monchengladbach",
        "Borussia Monchengladbach": "Borussia Monchengladbach",
        "Gladbach": "Borussia Monchengladbach",
        "Schalke": "Schalke 04",
        "Schalke 04": "Schalke 04",
        "Hertha": "Hertha Berlin",
        "Hertha Berlin": "Hertha Berlin",
        "Hoffenheim": "Hoffenheim",
        "TSG Hoffenheim": "Hoffenheim",
        "Freiburg": "Freiburg",
        "SC Freiburg": "Freiburg",
        "Stuttgart": "Stuttgart",
        "VfB Stuttgart": "Stuttgart",
        "Augsburg": "Augsburg",
        "FC Augsburg": "Augsburg",
        "Koln": "Koln",
        "FC Koln": "Koln",
        "Werder Bremen": "Werder Bremen",
        "Bremen": "Werder Bremen",
        "Hamburg": "Hamburg",
        "Hamburger SV": "Hamburg",
        "Mainz": "Mainz",
        "Mainz 05": "Mainz",
        "FSV Mainz 05": "Mainz",
        "Hannover": "Hannover 96",
        "Hannover 96": "Hannover 96",
        "Darmstadt": "Darmstadt",
        "Union Berlin": "Union Berlin",
        "Heidenheim": "Heidenheim",
        "St. Pauli": "St. Pauli",
        "Bochum": "Bochum",
        "VfL Bochum": "Bochum",
    },
    "F1": {
        "Paris Saint-Germain": "Paris Saint-Germain",
        "Paris SG": "Paris Saint-Germain",
        "PSG": "Paris Saint-Germain",
        "Lyon": "Lyon",
        "Olympique Lyonnais": "Lyon",
        "Marseille": "Marseille",
        "Olympique Marseille": "Marseille",
        "Monaco": "Monaco",
        "AS Monaco": "Monaco",
        "Nice": "Nice",
        "OGC Nice": "Nice",
        "Lille": "Lille",
        "LOSC Lille": "Lille",
        "Rennes": "Rennes",
        "Stade Rennes": "Rennes",
        "Stade Rennais": "Rennes",
        "Bordeaux": "Bordeaux",
        "Montpellier": "Montpellier",
        "Montpellier HSC": "Montpellier",
        "Nantes": "Nantes",
        "FC Nantes": "Nantes",
        "Saint-Etienne": "Saint-Etienne",
        "Saint-Etienne": "Saint-Etienne",
        "AS Saint-Etienne": "Saint-Etienne",
        "Strasbourg": "Strasbourg",
        "RC Strasbourg": "Strasbourg",
        "Nice": "Nice",
        "Lens": "Lens",
        "RC Lens": "Lens",
        "Brest": "Brest",
        "Stade Brestois": "Brest",
        "Toulouse": "Toulouse",
        "Toulouse FC": "Toulouse",
        "Reims": "Reims",
        "Stade de Reims": "Reims",
        "Metz": "Metz",
        "Lorient": "Lorient",
        "FC Lorient": "Lorient",
        "Amiens": "Amiens",
        "Amiens SC": "Amiens",
        "Dijon": "Dijon",
        "Dijon FCO": "Dijon",
        "Guingamp": "Guingamp",
        "AJ Auxerre": "Auxerre",
        "Sochaux": "Sochaux",
        "Valenciennes": "Valenciennes",
        "Le Havre": "Le Havre",
        "Le Havre AC": "Le Havre",
        "Clermont": "Clermont",
        "Clermont Foot": "Clermont",
        "Ajaccio": "Ajaccio",
        "AC Ajaccio": "Ajaccio",
        "Lyon": "Lyon",
    },
}


def normalize_team_name(name: str, league: str) -> str:
    """Normaliser un nom d'équipe vers le nom canonique.

    Args:
        name: Nom tel qu'il apparaît dans le CSV
        league: Code du championnat (E0, SP1, I1, D1, F1)

    Returns:
        Nom canonique normalisé

    """
    if not name or not isinstance(name, str):
        return name

    name_stripped = name.strip()
    aliases = TEAM_ALIASES.get(league, {})

    if name_stripped in aliases:
        return aliases[name_stripped]

    # Pas de correspondance : retourner le nom tel quel
    logger.warning(
        f"Nom d'équipe non reconnu : '{name_stripped}' dans la ligue {league}"
    )
    return name_stripped


def get_all_canonical_names() -> dict[str, list[str]]:
    """Retourner tous les noms canoniques par ligue."""
    result: dict[str, list[str]] = {}
    for league, aliases in TEAM_ALIASES.items():
        result[league] = sorted(set(aliases.values()))
    return result
